### ISSUE TITLE
Can't receive data

### ISSUE THREAD

**Issue by log3441** [antodom/soft_uart#1]
Hi. I really thank you for this library.
But I tried to receive rssi value using this, it didn't work.

Here is my code and I used two xbee modules.
This code is for printing rssi values among three xbee modules.
(The reason that I have to get more tx/rx pin is I will use 5 xbee modules in my project.)

`#include "soft_uart.h"
# define RX_PIN 10 // software serial port's reception pin
# define TX_PIN 11 // software serial port's transmision pin
# define SOFT_UART_BIT_RATE 9600 // 57600 38400 1200 19200 9600 115200 300
# define RX_BUF_LENGTH 256// software serial port's reception buffer length
# define TX_BUF_LENGTH 256// software serial port's transmision buffer length

using namespace arduino_due;

float Time, oldtime, del_t, distance1_filter_old, distance2_filter_old, IN1=51, IN2=52, in1, in2;
int i=0;
int j=0;

uint8_t rssi1, rssi2;
uint8_t trash1, trash2;

// declaration of software serial port object serial_tc4
// which uses timer/counter channel TC4
serial_tc4_declaration(RX_BUF_LENGTH,TX_BUF_LENGTH);
auto& serial_obj=serial_tc4; // serial_tc4_t& serial_obj=serial_tc4;

void setup() {

  Serial.begin(9600);

  // serial_obj initialization
  serial_obj.begin(
    RX_PIN,
    TX_PIN,
    SOFT_UART_BIT_RATE,
    soft_uart::data_bit_codes::EIGHT_BITS,
    soft_uart::parity_codes::EVEN_PARITY,
    soft_uart::stop_bit_codes::ONE_STOP_BIT
  );

  //Serial2.begin(9600);
  //Serial2.begin(SOFT_UART_BIT_RATE,SERIAL_8E1);
  Serial3.begin(9600);

  pinMode(IN1,OUTPUT); // IN1
  pinMode(IN2,OUTPUT); // IN2
  pinMode(8,OUTPUT); // PWM

  delay(100);

}

void loop() {

  Time = micros()*0.000001;
  del_t = Time - oldtime;

  while(Serial3.available()) 
  {
    trash1 = Serial3.read(); 
    if(trash1 == 0x81)
    {
      i++;
      continue;
    }
    if(i == 1)
    {
      i++;
      continue;
    }
    if(i == 2)
    {
      i++;
      continue;
    }
    if(i == 3)
    {
      if(trash1 > 20)
      {
      rssi1 = trash1;
      }
      i= 0;
    }
  }

  while(serial_obj.available())
  {
    trash2 = serial_obj.read(); 
    if(trash2 == 0x81)
    {
      j++;
      continue;
    }
    if(j == 1)
    {
      j++;
      continue;
    }
    if(j == 2)
    {
      j++;
      continue;
    }
    if(j == 3)
    {
      if(trash2 > 20)
      {
      rssi2 = trash2;
      }
      j= 0;
    }
  }

  digitalWrite(IN1,in1);
  digitalWrite(IN2,in2);

  Serial.print(" TIME;"); 
  Serial.print(Time,6);
  Serial.print("    "); 
  Serial.print("  RSSI1;");
  Serial.print(rssi1);
  Serial.print(" , ");
  Serial.print(" RSSI2;");
  Serial.println(rssi2);

  delay(10);
  oldtime = Time;

}`

Serial3's xbee printed value well, but serial_obj printed nothing(empty).
I don't know which one is wrong. Could you give me some advice?
Thank you.

**Comment by antodom** [comment]
What do you have connected to the serial_obj's pins?

**Comment by log3441** [comment]
I connected to the due pin n.10,11.
Also I tried other digital pins, for example 31,33

Isn't this library making pins to tx/rx pins?

**Comment by antodom** [comment]
Sorry, maybe I didn't make sense, the code seems ok, so check what you have connected to pins 10 and 11. The library is prepared for using any pair of pins, so that's no problem.

If you check the physical connections to the pins and they are ok, them check the configuration of the serial ports in the device you have connected to pins 10 and 11. It should match the configuration of the soft_uart object (9600 bauds, 8 bits, even parity and one stop bit).

**Comment by log3441** [comment]
Okay. Thanks for your kindly comment!
