### ISSUE TITLE
compiler ISO C++ 2011

### ISSUE THREAD

**Issue by antoniosap** [antodom/soft_uart#2]
compiling examples give me

..../packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/arm-none-eabi/include/c++/4.8.3/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

**Comment by antodom** [comment]
Hi there,

You should add flag -std=gnu++11 to the C++ compiler options in your Arduino IDE file platform.txt for the DUE. Usually, this flag is already activated if you are using Arduino IDE 1.6.6 or greater.

I hope it helps.

**Comment by antoniosap** [comment]
ok. thanks
