### ISSUE TITLE
linker: undefined reference to vtable

### ISSUE THREAD

**Issue by antoniosap** [antodom/soft_uart#3]
the linker give me strange error:

In function `HardwareSerial::HardwareSerial()':
......packages/arduino/hardware/sam/1.6.9/cores/arduino/HardwareSerial.h:26: undefined reference to`vtable for HardwareSerial'
collect2: error: ld returned 1 exit status

**Comment by antodom** [comment]
HardwareSerial is part of Arduino standard library, it comes with Arduino IDE, so ... did you change something inadvertently in platform.txt for the DUE?.

**Comment by antoniosap** [comment]
no, i dont change everything. examples compile fine. target source code give me this error

**Comment by antoniosap** [comment]
solved. i remove this 2 lines on top

#pragma GCC push_options
#pragma GCC optimize ("-O3")

**Comment by sdrshnptl** [comment]
Hi @antoniosap,
From which file you removed these files?

#pragma GCC push_options
#pragma GCC optimize ("-O3")

**Comment by antoniosap** [comment]
from my app file. incompatible pragmas
